// Generated by jextract

package cn.vanillazi.libappindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    static final FunctionDescriptor gtk_main$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle gtk_main$MH = RuntimeHelper.downcallHandle(
        "gtk_main",
        constants$2.gtk_main$FUNC
    );
    static final FunctionDescriptor app_indicator_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle app_indicator_get_type$MH = RuntimeHelper.downcallHandle(
        "app_indicator_get_type",
        constants$2.app_indicator_get_type$FUNC
    );
    static final FunctionDescriptor app_indicator_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle app_indicator_new$MH = RuntimeHelper.downcallHandle(
        "app_indicator_new",
        constants$2.app_indicator_new$FUNC
    );
    static final FunctionDescriptor app_indicator_new_with_path$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_new_with_path$MH = RuntimeHelper.downcallHandle(
        "app_indicator_new_with_path",
        constants$2.app_indicator_new_with_path$FUNC
    );
    static final FunctionDescriptor app_indicator_set_status$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle app_indicator_set_status$MH = RuntimeHelper.downcallHandle(
        "app_indicator_set_status",
        constants$2.app_indicator_set_status$FUNC
    );
    static final FunctionDescriptor app_indicator_set_attention_icon$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_set_attention_icon$MH = RuntimeHelper.downcallHandle(
        "app_indicator_set_attention_icon",
        constants$2.app_indicator_set_attention_icon$FUNC
    );
}


