// Generated by jextract

package cn.vanillazi.libappindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final FunctionDescriptor app_indicator_set_ordering_index$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle app_indicator_set_ordering_index$MH = RuntimeHelper.downcallHandle(
        "app_indicator_set_ordering_index",
        constants$4.app_indicator_set_ordering_index$FUNC
    );
    static final FunctionDescriptor app_indicator_set_secondary_activate_target$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_set_secondary_activate_target$MH = RuntimeHelper.downcallHandle(
        "app_indicator_set_secondary_activate_target",
        constants$4.app_indicator_set_secondary_activate_target$FUNC
    );
    static final FunctionDescriptor app_indicator_set_title$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_set_title$MH = RuntimeHelper.downcallHandle(
        "app_indicator_set_title",
        constants$4.app_indicator_set_title$FUNC
    );
    static final FunctionDescriptor app_indicator_get_id$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_get_id$MH = RuntimeHelper.downcallHandle(
        "app_indicator_get_id",
        constants$4.app_indicator_get_id$FUNC
    );
    static final FunctionDescriptor app_indicator_get_category$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_get_category$MH = RuntimeHelper.downcallHandle(
        "app_indicator_get_category",
        constants$4.app_indicator_get_category$FUNC
    );
    static final FunctionDescriptor app_indicator_get_status$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_get_status$MH = RuntimeHelper.downcallHandle(
        "app_indicator_get_status",
        constants$4.app_indicator_get_status$FUNC
    );
}


