// Generated by jextract

package cn.vanillazi.libappindicator;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$3 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$3() {}
    static final FunctionDescriptor app_indicator_get_attention_icon_desc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_get_attention_icon_desc$MH = RuntimeHelper.downcallHandle(
        "app_indicator_get_attention_icon_desc",
        constants$3.app_indicator_get_attention_icon_desc$FUNC
    );
    static final FunctionDescriptor app_indicator_get_title$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_get_title$MH = RuntimeHelper.downcallHandle(
        "app_indicator_get_title",
        constants$3.app_indicator_get_title$FUNC
    );
    static final FunctionDescriptor app_indicator_get_menu$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_get_menu$MH = RuntimeHelper.downcallHandle(
        "app_indicator_get_menu",
        constants$3.app_indicator_get_menu$FUNC
    );
    static final FunctionDescriptor app_indicator_get_label$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_get_label$MH = RuntimeHelper.downcallHandle(
        "app_indicator_get_label",
        constants$3.app_indicator_get_label$FUNC
    );
    static final FunctionDescriptor app_indicator_get_label_guide$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_get_label_guide$MH = RuntimeHelper.downcallHandle(
        "app_indicator_get_label_guide",
        constants$3.app_indicator_get_label_guide$FUNC
    );
    static final FunctionDescriptor app_indicator_get_ordering_index$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle app_indicator_get_ordering_index$MH = RuntimeHelper.downcallHandle(
        "app_indicator_get_ordering_index",
        constants$3.app_indicator_get_ordering_index$FUNC
    );
}


